# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in jfrog-saas-log-collector.gemspec
gemspec

gem "rake", "~> 13.0"

gem "minitest", "~> 5.0"

gem "rubocop", "~> 1.21"

gem "rest-client", "~> 2.1.0"

gem "faraday", "~> 2.2.0"
