apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jfrog-saas-log-collector-pvc
  labels:
    app: jfrog-saas-log-collector
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi