connection:
  jpd_url: "changeme"
  end_point_base: "artifactory"
  username: "changeme"
  access_token: "changeme"
  open_timeout_in_secs: 20
  read_timeout_in_secs: 60
log:
  log_ship_config: "access/api/v1/logshipping/config"
  solutions_enabled: ["artifactory", "xray"]
  log_types_enabled: ["access-request", "access-security-audit", "artifactory-request", "xray-request"]
  uri_date_pattern: "%Y-%m-%d"
  audit_repo: "artifactory/jfrog-logs-audit"
  log_repo: "artifactory/jfrog-logs"
  target_log_path: "changeme"
  debug_mode: false
  print_with_utc: true
  log_file_retention_days: 5
process:
  parallel_process: 2
  parallel_downloads: 5
  historical_log_days: 3
  write_logs_by_type: false
  minutes_between_runs: 180
  